### ISSUE TITLE
Webpack error loading picture when compiling but not with HMR

### ISSUE THREAD

**Issue by ibobcode** [jgliner/react-router-v4-redux-ssr#3]
Hi men! First of all : **GREAT** work, really.
I just wanted to know how you import images on this boilerplate because maybe I'm doing it the wrong way.
So, first, what I do in one of :
`import pic from './mydamnpicture.jpg';`
And here is the error i'm getting : 
`SyntaxError: /path/src/containers/mydamnpicture.jpg: Unexpected character '�' (1:0)`
I'm pretty sure every one who have messed a bit with webpack recognise this as it is a common error message when you are not using url-loader or file-loader plugin.
**BUT** this is not the case here, file-loader is there!
**And moreover** the following css code in a css file works fine : 
`background-image: url('./mydamnpicture.png');`

And now one more thing : I delete the import line, compile, everything works fine exept I have just my picture missing on my web app... **THEN** I re-add the import line, HMR does it's work and oooooh surprise the picture appears, no crash in the logs...

Ok so now just one last word : HELP 😂

**Comment by ibobcode** [comment]
Ok I made some progress : now I got it to work in production mode configuring a bit `file-loader` and adding `babel-plugin-file-loader` !
But still with HMR I have some problems : no compile error this time but all the images are loaded in the dist folder like in production and HMR is apparently not fining them this way because nothing shows up on the web page... 

Still looking for some advises if you have some! :)

**Comment by jgliner** [comment]
Hi! Thanks for the kind words. Sorry I haven't been on here much lately (My job doesn't use GH to host their git repos)

Importing images works in sort of a strange way. Typically, you'd use a CDN like S3 to serve images, but if you want to serve them as static content, all you need to do is insert an `<img>` element with the `src` as a relative path inside of your repo. Then, in the server, specify that directory with `express.static`. This may not be best practice, however, so if anyone has a better (or pure Webpack) solution, I'm definitely open to it.

See below:

_File Structure_
```
(Root)
|_ src
  |_ ComponentName.js
|_ assets
  |_ mydamnpicture.jpg
|_ server
  |_ server.js
```

**ComponentName.js**
```jsx
  <img src="./mydamnpicture.jpg"></img>
```

**Server.js**
```js
app.use('/assets', express.static(path.join(__dirname, '../assets/')));
```
Hope this helps!
